name: Ali AVD Crawl

on:
  # Execute at 2:00, 10:00 and 18:00 Beijing time (UTC+8) every day
  # Same as UTC time in cron
  schedule:
    - cron: '0 2,10,18 * * *'
  # Manually trigger workflow
  workflow_dispatch:

jobs:
  crawl:
    name: Get CVE info from ali avd database
    runs-on: ubuntu-20.04
    env:
      # set system timezone
      TZ: Asia/Shanghai
    steps:
      - name: Check out code into the root directory
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python code
        env:
          ALI_AVD_TOKEN: ${{ secrets.ALI_AVD_TOKEN }}
        run: python run.py
